### ISSUE TITLE
Request blocked without source_url specified

### ISSUE THREAD

**Issue by dexpota** [brave/adblock-rust#171] opened 2021-05-14 10:19 UTC
I was tinkering with this library and by looking at the test code I think I might have found a possible issue. I forked the repository and added some test code that I think should fail but it does not. This is the code I added to `check_third_party_script` inside `legacy_harness.rs` (here is the [diff](https://github.com/brave/adblock-rust/compare/master...dexpota:master)).

```
        // explicit, separate testcase construction of the "script" option as it is not the deafult
        let filter = NetworkFilter::parse("||googlesyndication.com/safeframe/$third-party,script", true).unwrap();
        let filter2 = NetworkFilter::parse("||googlesyndication.com/safeframe/$~third-party,script", true).unwrap();
        let filter3 = NetworkFilter::parse("||googlesyndication.com/safeframe/$first-party,script", true).unwrap();
        let filter4 = NetworkFilter::parse("||googlesyndication.com/safeframe/$script", true).unwrap();
        let request = Request::from_urls("http://tpc.googlesyndication.com/safeframe/1-0-2/html/container.html#xpc=sf-gdn-exp-2&p=http%3A//slashdot.org;", "", "script").unwrap();
        assert!(filter.matches(&request));
        assert!(filter2.matches(&request));
        assert!(filter3.matches(&request));
        assert!(filter4.matches(&request));
```

Shouldn't `filter`, `filter2`, `filter3` fail, and `filter4` succeed? When `source_url` is not specified, we should not match with a rule that explicitly filters only `third_party` requests.

**Comment by ArniDagur** [comment] 2021-05-14 11:59
This is a bug we needed to work around in Qutebrowser as well. See https://github.com/qutebrowser/qutebrowser/blob/ac12fcd714c699f927170b3d0508336940366bac/qutebrowser/components/braveadblock.py#L153

**Comment by ArniDagur** [comment] 2021-05-14 12:00
Also, I think this is a duplicate of https://github.com/brave/adblock-rust/issues/146

**Comment by antonok-edm** [comment] 2021-05-15 04:23
Yep, this is a duplicate of #146 - `source_url` is required. I'll close this, but feel free to move conversation there.

**Closed by antonok-edm** 2021-05-15 04:23 UTC
