### ISSUE TITLE
Filters containing `$$` don't parse correctly

### ISSUE THREAD

**Issue by Emi-TheDhamphirInLoveUnderTheFrozenStar** [brave/adblock-rust#299] opened 2023-07-10 22:10 UTC
Hey @antonok-edm, I found an issue with parsing the scriptlets values when it starts with `$` symbol.

if the value in a scriptlet is for example: `$remove$`, the result will only be parsed as a single `$`

But If the value is `$ remove`, it parses as `$ remove`

The problem is [set-local/session-storage-item scriptlets](https://github.com/gorhill/uBlock/blob/4a570c151fe4ce426c5fb140c76c944218ed5692/assets/resources/scriptlets.js#L759) has an important feature to remove the items by using `$remove$` value, and it won't work in Brave until this is not fixed.

The issue is exclusive to only `$` symbol because I tested other symbols and everything was parsed as in the custom rule.
But, it can be tested with any scriptlet, because what matters is what Devtools scriptlets source displays.

So, for example, when using `$whatever` as value it should display as:
![image](https://github.com/brave/adblock-rust/assets/122518587/b52e63c6-c9e2-4361-8624-4fa8d53aa9e6)

And like I said, if there is a space after the `$ `, then it looks fine, since it doesn't remove anything and displays as the custom rule. Useless but it works.
![image](https://github.com/brave/adblock-rust/assets/122518587/8e5f75f6-0ecd-4045-acca-01ef7e87cc0f)

**Also, when using `$$remove$$`, the scriptlet completely break, and it is like if the rule didn't exist at all, because the scriptlet doesn't even show in the sources devtools.**

# How to reproduce it:
1. Add `brave.com##+js(set-local-storage-item, Test, 0)` as a custom rule or go to Brave, or use `localStorage.setItem("Test", "0");` to create `Test` with value `0`.
2. now replace or add the custom rule with `brave.com##+js(set-local-storage-item, Test, $remove$)`
3. go to Devtools -> Application -> Local Storage
4. The local item is still there and doesn't get removed as it should.

**Comment by antonok-edm** [comment] 2023-07-18 01:57
@Emi-TheDhamphirInLoveUnderTheFrozenStar great catch, thanks!

I've narrowed it down to the use of `Regex::replace` - as per the [docs](https://docs.rs/regex/latest/regex/struct.Regex.html#method.replace), `$` is interpreted as a special character;
> To write a literal `$` use `$$`.

By that logic, writing `$$remove$$` _should_ fix it, although as you've noted it gets completely ignored. That's ultimately caused by [this](https://github.com/brave/adblock-rust/blob/master/src/lists.rs#L511-L515) piece of code to ignore AdGuard-specific `$$` syntax.

Both cases can definitely be improved.

**Comment by antonok-edm** [comment] 2023-07-18 02:19
48b6b5ecbc4393d9b6ec6cfe93e4897f831d2e28 should take care of the first issue. I think the second is less likely to cause problems but I'll take another look at it again later.

**Comment by antonok-edm** [comment] 2023-07-26 18:58
The `$$` issue should be fixed with https://github.com/brave/adblock-rust/commit/96911ee255b614cbdcb62200098259bd69235242.

**Closed by antonok-edm** 2023-07-26 18:58 UTC
Labels: bug
